### PR TITLE
fix(frontend): relaxes cookie restricitions in dev

### LINKED ISSUE #2095: Auth cookies don't seem to be stored in Safari preventing login

### PR DESCRIPTION
**Pull request by anupcowkur**
# Description

Safari has stricter requirements than chrome for localhost. This commit relaxes the requirements in dev environment so dashboard can function effectively using Safari.

## Related issue
Fixes #2095

### CODE REVIEW

File: frontend/dashboard/app/auth/cookie.ts [hunk 1]
```diff
@@ -1,38 +1,40 @@
...
     })
 
     response.cookies.set('refresh_token', refreshToken, {
         path: '/',
         domain: domain,
         maxAge: Math.floor((refreshExp.getTime() - Date.now()) / 1000),
         httpOnly: true,
-        secure: true,
-        sameSite: 'strict',
+        secure: !isDev,
```
Comment (detj) [inline frontend/dashboard/app/auth/cookie.ts:36]: @anupcowkur All browsers, including Safari should ignore `secure: true` for local context (localhost). So, you can leave it to `true` as was before. Should work.

image

https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Set-Cookie#secure
