### PR TITLE
Ios session creation

### LINKED ISSUE #1375: Update session creation logic
As part of https://github.com/measure-sh/measure/pull/1372, the way sessions are created has changed. There are two major changes:

1. On SDK initialization, create a new session if last event was triggered more than `sessionEndThresholdMs` ago, else continue previous session. Except when the last session ended in a crash.
2. Similarly if app comes back to foreground, create new session if the last event was triggered more than the threshold time, else continue existing session.
3. Increase `sessionEndLastEventThresholdMs` from 1 minute to 20 minutes.
4. Add a new config `maxSessionDurationMs` with default value as 6 hours.
5. Create a new session when app comes back to foreground or when app is launched from scratch if the previous session has already lasted for `maxSessionDurationMs`.

### PR DESCRIPTION
**Pull request by adwinross**
# Description

Session creation logic updated. If the app is restarted within 20 minutes, the previous session is continued.

A maximum session length threshold has also been added. I the session continues for more than 6 hours, the session is ended whenever the app moves to foreground or the app is restarted.

`SystemTime` has been removed as `TimeProvider` is already doing the time related operations.

## Related issue
Closes #1375

### CODE REVIEW

File: ios/MeasureSDK/SessionManager.swift [hunk 1]
```diff
@@ -44,29 +48,64 @@ final class BaseSessionManager: SessionManager {
...
+        }
+        return nil
+    }
+
+    private func isSessonDurationThreadholdReached() -> Bool {
+        guard let recentSession = userDefaultStorage.getRecentSession() else {
+            return false
+        }
+
+        return (timeProvider.currentTimeSinceEpochInMillis - recentSession.createdAt) >= configProvider.maxSessionDurationMs
```
Comment (abhaysood) [inline ios/MeasureSDK/SessionManager.swift:96]: Add a check for negative time difference to handle any clock skew issues.

**Review by abhaysood — APPROVED** [review]
