### PR TITLE
fix(ios): only call functions if sdk is started

### LINKED ISSUE #2582: SDK apis should be inaccessible is SDK is not started

### PR DESCRIPTION
**Pull request by adwinross**
# Description

SDK apis should be inaccessible is SDK is not started

## Related issue
Fixes #2582

### CODE REVIEW

File: ios/Sources/MeasureSDK/Swift/MeasureInternal.swift [hunk 1]
```diff
@@ -175,78 +175,104 @@ final class MeasureInternal { // swiftlint:disable:this type_body_length
...
     }
 
     func startSpan(name: String, timestamp: Int64? = nil) -> Span {
+        guard isStarted else { return InvalidSpan() }
+
         return spanCollector.startSpan(name: name, timestamp: timestamp)
     }
 
     func getTraceParentHeaderValue(for span: Span) -> String {
+        guard isStarted else { return "" }
```
Comment (abhaysood) [inline ios/Sources/MeasureSDK/Swift/MeasureInternal.swift]: We can return a valid value here as it's just a convenience function, can be used whether or not the SDK is started.

File: ios/Sources/MeasureSDK/Swift/MeasureInternal.swift [hunk 2]
```diff
@@ -175,78 +175,104 @@ final class MeasureInternal { // swiftlint:disable:this type_body_length
...
+
         return spanCollector.getTraceParentHeaderValue(for: span)
     }
 
     func getTraceParentHeaderKey() -> String {
+        guard isStarted else { return "" }
```
Comment (abhaysood) [inline ios/Sources/MeasureSDK/Swift/MeasureInternal.swift]: We can return a valid value here as it's just a convenience function, can be used whether or not the SDK is started.

File: ios/Sources/MeasureSDK/Swift/MeasureInternal.swift [hunk 3]
```diff
@@ -255,27 +281,37 @@ final class MeasureInternal { // swiftlint:disable:this type_body_length
...
 
     func trackError(_ error: NSError, attributes: [String: Any]? = nil, collectStackTraces: Bool) {
+        guard isStarted else { return }
+
         let transformedAttributes = transformAttributes(attributes)
         userTriggeredEventCollector.trackError(error, attributes: transformedAttributes, collectStackTraces: collectStackTraces)
     }
 
     func getDocumentDirectoryPath() -> String? {
+        guard isStarted else { return nil }
```
Comment (abhaysood) [inline ios/Sources/MeasureSDK/Swift/MeasureInternal.swift]: We can return a valid value here as it's just a convenience function, can be used whether or not the SDK is started.

File: ios/Sources/MeasureSDK/Swift/MeasureInternal.swift [hunk 4]
```diff
@@ -175,78 +175,104 @@ final class MeasureInternal { // swiftlint:disable:this type_body_length
...
+        guard isStarted else { return }
+
         userAttributeProcessor.setUserId(userId)
     }
 
     func clearUserId() {
+        guard isStarted else { return }
+
         userAttributeProcessor.clearUserId()
     }
```
Comment (abhaysood) [inline ios/Sources/MeasureSDK/Swift/MeasureInternal.swift]: These two methods on Android are currently allowed, even if the SDK is not started to allow setting up state when needed. We could allow this even if SDK is not started.

**Review by abhaysood — CHANGES_REQUESTED** [review]
The started check is primarily needed to ensure that no events/traces are collected. We can still allow some functions to continue working.

**Review by abhaysood — APPROVED** [review]
