### PR TITLE
fix(ios): update process start time logic

### LINKED ISSUE #2561: Incorrect launch times
https://staging.measure.sh/e89cc035-620e-494a-8e33-e45334c84944/sessions/3bef3db6-0590-41e4-bc0b-c0253c8249da/1df2b36b-1975-4176-9740-f182435cc51c
Image

### PR DESCRIPTION
**Pull request by adwinross**
# Description

This PR fixes incorrect launch time by updating the below things:

- Update sysCtl's `getProcessStartTime` to provide more accurate process start time.
- Ignore launch time collection if the app is [pre-warmed](https://developer.apple.com/documentation/uikit/about-the-app-launch-sequence#Prepare-your-app-for-prewarming)
- Use `timeProvider` instead of `Date().timeIntervalSince1970`

## Related issue
Fixes #2561

### CODE REVIEW

File: ios/Sources/MeasureSDK/Swift/AppLaunch/LaunchTracker.swift [hunk 1]
```diff
@@ -74,22 +75,29 @@ final class BaseLaunchTracker: LaunchTracker {
             return
         }
 
+        guard !isActivePrewarm else {
```
Comment (adwinross) [inline ios/Sources/MeasureSDK/Swift/AppLaunch/LaunchTracker.swift:78]: Add documentation

**Review by abhaysood — APPROVED** [review]
